CREATE TABLE objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    target_date DATE,
    target_value DECIMAL(19, 2),
    creation_date DATE
);